version: '2'
# Kong
services:
  kong-database:
    image: postgres:9.4
    environment:
      - POSTGRES_USER=kong
      - POSTGRES_DB=kong

  kong:
    build: kong
    depends_on:
      - kong-database
    environment:
      - KONG_DATABASE=postgres
      - KONG_PG_HOST=kong-database

  nginx:
    build: nginx
    depends_on:
      - kong
    expose:
      - 8000
      - 8001
      - 8443
    ports:
      - 8000:8000
      - 8001:8001
      - 8443:8443
